# Site settings
title: Nicole Beholz
email: nicole.beholz@googlemail.com
url: https://nicolebeholz.com
description: "Freelance support for ideation, concept development, project management, and process optimization."
skills: "Creative Concepts & Project Management"
meta_author: Nicole Beholz

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nicole Beholz
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nicole-beholz-61aa6151
  - title: twitter
    url: http://twitter.com/nicktoolate
  - title: instagram
    url: http://instagram.com/nicktoolate

# Postal address (add as many lines as necessary)
address:
  - line: Große Freiheit 69
  - line: 22767 Hamburg
  - line: Germany

# Credits content
credits: 'Design based on “Freelancer” theme by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
